(defun SayingHello()
    (terpri)
    (princ "HH    HH   EEEEEEEE   LL     LL       OOOO")
    (terpri)
    (princ "HH    HH   EE         LL     LL     OO    OO")
    (terpri)
    (princ "HHHHHHHH   EEEEEEEE   LL     LL     OO    OO")
    (terpri)
    (princ "HH    HH   EE         LL     LL     OO    OO")
    (terpri)
    (princ "HH    HH   EEEEEEEE   LLLLL  LLLLL    OOOO")
    (TERPRI)
  )
